### PR TITLE
rev to 1.0.3 in prep for publishing

### PR DESCRIPTION
**Pull request by devoncarew**
- rev to `1.0.3` in prep for publishing

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
Do we really need to publish this?

...I guess to get the runtime upside...

**Comment by devoncarew** [comment]
> I guess to get the runtime upside

Yup, I think it's worth it for that.

I'll convert this PR to a draft however - sounds like we're waiting on one more PR to land.

**Comment by natebosch** [comment]
I bumped to a feature version in f6979e3bc3b6e1847a08335b7eb6304e18986195

We'll need to wait for this to land in the SDK and internally before we can publish.

**Comment by devoncarew** [comment]
> I bumped to a feature version in [f6979e3](https://github.com/dart-lang/logging/commit/f6979e3bc3b6e1847a08335b7eb6304e18986195)

Gotcha, I'll close this.

> We'll need to wait for this to land in the SDK and internally before we can publish.

Is that to validate the changes before we publish?

**Comment by natebosch** [comment]
> Is that to validate the changes before we publish?

Yes. https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#publishing-a-package

We want to take advantage of our much larger set of tests, and prevent issues where packages can't be synced and we need to consider rolling back features because we find they are incompatible with too much code.

**Pull request closed without merging**
