### PR TITLE
log levels - support for ERROR, DEBUG and CRITICAL levels

### LINKED ISSUE #23: Add "error" and "info"-method to Logger
_From @DartBot on July 16, 2013 13:12_

_This issue was originally filed by off...&#064;mikemitterer.at_

---

**What steps will reproduce the problem?**
final Logger logger = new Logger(&quot;rest.DefeaultRESTErrorProcessor&quot;);
logger.error(&quot;Does not work&quot;);

**Please provide any additional information below.**
Most Logging-Frameworks use &quot;error&quot; to print out error-messages.
You use &quot;severe&quot;, this is OK but give us &quot;error&quot; to.

The same with &quot;info&quot; - I don't know who is using fine, finer, finest - means nothing.
fine, finer, finest???? - please provide us with &quot;info&quot; in addition to &quot;fine&quot;

_Copied from original issue: dart-lang/sdk#11845_

### PR DESCRIPTION
**Pull request by jossef**
fixes #23

### CODE REVIEW

**Comment by kevmoo** [comment]
@natebosch @jakemac53 – thoughts here?

**Comment by jakemac53** [comment]
Also consider code that is try to catch error messages today... they could be doing that one of three common ways.

- check if the level is > Level.WARNING (would still work)
- check if the level is exactly Level.SEVERE (would not catch ERROR/CRITICAL)
- use a switch statement to handle each level explicitly (would not catch the new levels)

Only the first of those options would not be broken by this change.

My opinion is that the value proposition of this change doesn't outweigh the cost of it (in terms of the breaking change). As far as I see it the value proposition is purely convenience (clearer naming), there are more than enough levels already to sufficiently handle a variety of severity levels.

**Comment by kevmoo** [comment]
Thanks for the breakdown, @jakemac53 . Going to close this out. Good thinking here, @jossef , but this is a very stable package. We can't rock the boat.

**Comment by jossef** [comment]
Thanks @kevmoo and @jakemac53.

What if I'll only create aliases for the `critical`, `error` and `debug` levels;
-  ERROR -> SEVERE
-  CRITICAL -> SHOUT
-  DEBUG -> FINE 

would it be acceptable? 

as a user, I miss the joy of using API such as `logging.error(...)` / `logging.debug(...)`

**Comment by jakemac53** [comment]
We could consider the aliases... I am not sure if it would lead to confusion or not.

I am also not sure what level `DEBUG` should actually log at? Currently the docs for `SHOUT` say "Key for extra debugging loudness". But, you generally don't want the debug things showing up in user logs so I get why fine/finer/finest would also make sense. SHOUT is also a bit weird in that it is I think the only place we diverge from [java.util.logging](https://docs.oracle.com/javase/8/docs/api/java/util/logging/class-use/Level.html#java.util.logging), it doesn't exist there.

**Pull request closed without merging**
