### PR TITLE
Added metaData field to LogRecord and log functions (#115)

### PR DESCRIPTION
**Pull request by AmanNegi**
Hey, there I have added the `metaData` field as requested in Issue (#115). Places I have made changes are the `LogRecord` class and in all the logging functions.

### CODE REVIEW

**Comment by devoncarew** [comment]
@AmanNegi - thanks for the contribution! We generally have to be conservative with API additions to this package - it's widely used in the ecosystem and implemented in a few other packages. I'd like to get a better sense of the potential impact of this change before we move forward with something like it (so, there will be a bit of a delay before we could review this PR).

**Comment by AmanNegi** [comment]
Okay sure @devoncarew. Let me know if some changes are needed at my end.

**Comment by feinstein** [comment]
I think the Metadata parameter should be an `Object?` as well, to keep it consistent with the rest of the API.

**Comment by robsonsilv4** [comment]
Hi @devoncarew, any updates on this proposal?

**Comment by AmanNegi** [comment]
Give me a moment I'll update this in a while.

**Comment by feinstein** [comment]
I think you will have better changes to get this to be approved if you didn't change the formatting.

**Comment by AmanNegi** [comment]
> I think you will have better changes to get this to be approved if you didn't change the formatting.

Sure, I have updated the formatting, to the default format.

**Comment by mosuem** [comment]
Closing as the [dart-lang/logging](https://github.com/dart-lang/logging) repository is merged into the [dart-lang/core](https://github.com/dart-lang/core) monorepo. Please re-open this PR there!

**Pull request closed without merging**
