### PR TITLE
Support Dart 2.11

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by jakemac53** [comment]
Do we need this? We are going to be changing constraints to `>=2.12.0.0 <3.0.0` soon.

**Comment by kevmoo** [comment]
> Do we need this? We are going to be changing constraints to `>=2.12.0.0 <3.0.0` soon.

Getting travis green in the mean time

**Comment by jakemac53** [comment]
I went ahead and just merged as this doesn't hurt for now

**Pull request merged**
